// students-and-groups/client/src/app/groups/groups/group-table/group-table.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Student} from '../../../models/student';
import {GroupService} from '../../group.service';
import {Group} from '../../../models/group';

@Component({
  selector: 'app-group-table',
  templateUrl: './group-table.component.html',
  styleUrls: ['./group-table.component.scss']
})
export class GroupTableComponent implements OnInit {
  groupNumbers: number[];
  students: Student[];

  constructor(private groupService: GroupService) {
  }

  private _groupNumber: number;

  @Input() set groupNumber(value: number) {
    this.students = [];
    this._groupNumber = value;
    if (this.groupNumber === 0) {
      this.groupService.getStudentsWithoutGroupId().subscribe((data: Student[]) => this.students = data);
    } else {
      this.groupService.getStudentWithGroupId(this.groupNumber).subscribe((data: Student[]) => this.students = data);
    }
  }

  get groupNumber(): number {

    return this._groupNumber;

  }

  ngOnInit(): void {
    this.groupNumbers = [0, 1, 2, 3, 4, 5, 6];
    if (this.groupNumber === 0) {
      this.groupService.getStudentsWithoutGroupId().subscribe((data: Student[]) => this.students = data);
    } else {
      this.groupService.getStudentWithGroupId(this.groupNumber).subscribe((data: Student[]) => this.students = data);
    }
  }

  assignStudentToGroupByGroupNumber(student: Student, groupNumber: number) {
    this.groupService.assignStudentToGroupId(student._id, groupNumber).subscribe(
      (data: Group) => {
        this.students = this.students.filter(s => s._id !== data.student);
      }
    );
  }

  unAssignStudentFromGroup(student: Student) {
    this.groupService.unAssignStudentFromGroupId(student._id).subscribe(
      () => {
        this.students = this.students.filter(s => s._id !== student._id);
      }
    );
  }

}

<table class="table mt-4" *ngIf="groupNumber === 0">
  <thead>
  <tr>
    <th>
      Lastname
    </th>
    <th>
      Firstname
    </th>
    <th>
      Student Number
    </th>
    <th>
      Actions
    </th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let student of students">
    <th>
      {{student.lastname}}
    </th>
    <th>
      {{student.firstname}}
    </th>
    <th>
      {{student.studentNumber}}
    </th>
    <th>
      <button class="button"
              style="border-radius: 50%; margin-right: 1rem" *ngFor="let gn of groupNumbers">
                                    <span class="icon is-small" (click)="assignStudentToGroupByGroupNumber(student, gn)">
    {{gn}}
    </span>
      </button>
    </th>
  </tr>
  </tbody>
</table>
<table class="table mt-4" *ngIf="groupNumber !== 0">
  <thead>
  <tr>
    <th>
      Lastname
    </th>
    <th>
      Firstname
    </th>
    <th>
      Student Number
    </th>
    <th>
      Actions
    </th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let student of students">
    <th>
      {{student.lastname}}
    </th>
    <th>
      {{student.firstname}}
    </th>
    <th>
      {{student.studentNumber}}
    </th>
    <th>
      <button class="button is-danger" (click)="unAssignStudentFromGroup(student)">
                                        <span class="icon is-small">
                                         <i class="fas fa-times-circle"></i>
                                        </span>
      </button>
    </th>
  </tr>
  </tbody>
</table>

// students-and-groups/client-react/src/components/groups/group-table/GroupTable.jsx
import React, { useEffect, useState } from 'react';
import axios from '../../../api/server';
import PopUpNotification from '../../popup/Popup';

const GroupTable = ({ groupNumber }) => {
  const [students, setStudents] = useState([]);
  const groupNumbers = [1, 2, 3, 4, 5, 6];
  const [actionDescriptionText, setActionDescriptionText] = useState('');

  const setStudentToGroupNumber = async (student, groupNumber) => {
    try {
      const response = await axios.post(
        `/groups/${groupNumber}/students/${student._id}`
      );
      if (response.status === 201) {
        setStudents(students.filter((s) => s._id !== student._id));
        setActionDescriptionText(
          `Student ${student.firstname} ${student.lastname} with student number: ${student.studentNumber} ASSIGNED to group ${groupNumber}`
        );
        setTimeout(() => {
          setActionDescriptionText('');
        }, 2000);
      }
    } catch (e) {
      console.log(e);
    }
  };

  const unAssignStudentFromGroup = async (student) => {
    try {
      const response = await axios.patch(`/groups/students/${student._id}`);
      if (response.status === 200) {
        setStudents(students.filter((s) => s._id !== student._id));
        setActionDescriptionText(
          `Student ${student.firstname} ${student.lastname} with student number: ${student.studentNumber} REMOVED from group ${groupNumber}`
        );
        setTimeout(() => {
          setActionDescriptionText('');
        }, 2000);
      }
    } catch (e) {
      console.log(e);
    }
  };

  useEffect(() => {
    setStudents([]);
    if (groupNumber === 0) {
      axios
        .get('/groups/students')
        .then((res) => {
          return res.data;
        })
        .then((data) => {
          console.log(data);
          setStudents(data);
        })
        .catch((e) => {
          console.log(e);
        });
    } else {
      axios
        .get(`/groups/${groupNumber}/students`)
        .then((res) => {
          return res.data;
        })
        .then((data) => {
          console.log(data);
          setStudents(data);
        })
        .catch((e) => {
          console.log(e);
        });
    }
  }, [groupNumber]);

  return (
    <>
      {actionDescriptionText && (
        <PopUpNotification>
          <div>{actionDescriptionText}</div>
        </PopUpNotification>
      )}
      <table className='table mt-4'>
        <thead>
          <tr>
            <th>Lastname</th>
            <th>Firstname</th>
            <th>Student Number</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {students.map((student) => (
            <tr key={student._id}>
              <th>{student.lastname}</th>
              <th>{student.firstname}</th>
              <th>{student.studentNumber}</th>
              {groupNumber === 0 ? (
                <th>
                  {groupNumbers.map((groupNumber) => (
                    <button
                      className='button'
                      key={groupNumber}
                      style={{ borderRadius: '50%', marginRight: '1rem' }}
                      onClick={() => {
                        setStudentToGroupNumber(student, groupNumber);
                      }}
                    >
                      <span className='icon is-small'>{groupNumber}</span>
                    </button>
                  ))}
                </th>
              ) : (
                <th>
                  <button
                    className='button is-danger'
                    onClick={() => unAssignStudentFromGroup(student)}
                  >
                    <span className='icon is-small'>
                      <i className='fas fa-times-circle' />
                    </span>
                  </button>
                </th>
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
};

export default GroupTable;
