// students-and-groups/client-react/src/components/groups/Groups.jsx
import React, {useState} from 'react'
import GroupTable from "./group-table/GroupTable";

const Groups = () => {
    const groupNumbers = [0, 1, 2, 3, 4, 5, 6]
    const [groupNumber, setGroupNumber] = useState(0)

    return (
        <div style={{display: 'flex'}}>
            <section className="main-content columns is-fullheight sidebar" style={{minWidth: '15rem', maxWidth: '100%'}}>
                <aside className="column is-narrow-mobile is-fullheight section is-hidden-mobile">
                    <p className="menu-label is-hidden-touch">Group number</p>
                    <ul className="menu-list">
                        {
                            groupNumbers.map(groupNumber => (
                                <li key={groupNumber} onClick={() => setGroupNumber(groupNumber)}>

                                    {
                                        groupNumber === 0 ? (
                                                <a href="#" className=""><span className="icon"><i className="fa fa-user"/></span> No group
                                                </a>
                                            )
                                            :
                                            (
                                                <a href="#" className=""><span className="icon"><i
                                                    className="fa fa-user"/></span> Group {groupNumber}</a>
                                            )
                                    }

                                </li>
                            ))
                        }
                    </ul>
                </aside>
            </section>
            <GroupTable groupNumber={groupNumber}/>
        </div>
    )
}

export default Groups

// students-and-groups/client/src/app/groups/groups/groups.component.ts
import {Component, OnChanges, OnInit, SimpleChanges} from '@angular/core';

@Component({
  selector: 'app-groups',
  templateUrl: './groups.component.html',
  styleUrls: ['./groups.component.scss']
})

export class GroupsComponent implements OnInit {

  groupNumbers: number[];
  groupNumber: number;

  constructor() {
  }

  ngOnInit(): void {
    this.groupNumbers = [0, 1, 2, 3, 4, 5, 6];
    this.groupNumber = 0;
  }

  setGroupNumber(groupNumber) {
    this.groupNumber = groupNumber;
  }

}

<div style="display: flex">
  <section class="main-content columns is-fullheight sidebar" style="min-width: 15rem; max-width: 100%">
    <aside class="column is-narrow-mobile is-fullheight section is-hidden-mobile">
      <p class="menu-label is-hidden-touch">Group number</p>
      <ul class="menu-list">
        <li (click)="setGroupNumber(groupNumber)" *ngFor="let groupNumber of groupNumbers">
          <a *ngIf="groupNumber === 0"><span class="icon"><i class="fa fa-user"></i></span> No group
          </a>
          <a *ngIf="groupNumber !== 0"><span class="icon"><i
            class="fa fa-user"></i></span> Group {{groupNumber}}</a>
        </li>
      </ul>
    </aside>
  </section>
  <app-group-table [groupNumber]="groupNumber" style="width: 100%"></app-group-table>
</div>
